Improved Quiz Selection & New version of the Blockchain game
dgusakov/bimbimon-landing pull request #56
Opened 2023-07-23 19:36 UTC by larmork

**Improvement of random selection in Quiz game:** now the questions are generated randomly, but not repeated, when the questions end, the user can restart the quiz.
**Improvement of the Blockchain game:** now the assembled puzzle has become colored, it is now possible to cancel the selection by double-clicking, a hint button and a game restart button have also appeared

2023-08-03 07:50 UTC, dgusakov requested changes
Not a full review. Will finalise it later

2023-08-03 07:50 UTC, dgusakov commented on src/components/App.tsx
> +            <Route path="/blockchain" element={<Blockchain />} />
What is the purpose of the route?

2023-08-03 07:50 UTC, dgusakov commented on src/components/Question.tsx
> +              <div id="questionBody">Все вопросы из этой темы уже показаны.</div>
We heed a "start over" button here

2023-08-03 07:50 UTC, dgusakov commented on src/components/Question.tsx
> +              <div id="questionBody">Все вопросы из этой темы уже показаны.</div>
Or I didn't get the idea. Is it a placeholder for the cases of no questions at all? Then change text

2023-08-03 07:50 UTC, dgusakov commented on src/components/QuizMain.tsx
> +        <ListItem displayName="<Больше книг-игр уже скоро>!" />
What are these symbols for?

2023-08-05 12:53 UTC, larmork commented on src/components/App.tsx
> +            <Route path="/blockchain" element={<Blockchain />} />
Forgot to delete

2023-08-05 12:55 UTC, larmork commented on src/components/QuizMain.tsx
> +        <ListItem displayName="<Больше книг-игр уже скоро>!" />
Idk, just typo

2023-08-05 13:05 UTC, larmork commented on src/components/Question.tsx
> +              <div id="questionBody">Все вопросы из этой темы уже показаны.</div>
So, if there are no questions to show, we'll display "start over" button?

2023-12-07 13:16 UTC, dgusakov requested changes

2023-12-07 13:16 UTC, dgusakov commented on src/css/App.css
> +.button-2 {
Same as button-1

2023-12-07 13:16 UTC, dgusakov commented on src/components/Question.tsx
> +              </button>
Keep only "Start over" button

2023-12-07 13:16 UTC, dgusakov commented on src/components/Question.tsx
> +              <div id="questionBody">Все вопросы из этой темы уже показаны.</div>
Change text to "Вопросов по теме не найденно"

2023-12-07 15:53 UTC, larmork commented on src/css/App.css
> +.button-1 {
fixed

2023-12-07 15:53 UTC, larmork commented on src/css/App.css
> +.button-2 {
fixed

2023-12-15 08:17 UTC, dgusakov approved these changes

2023-12-15 08:17 UTC, merged